### PR TITLE
Upgrade to 4.0.0

### PR DESCRIPTION
**Pull request by Protosac**
This update is required for the Django 1.10 upgrade.

https://github.com/pinax/pinax-notifications/issues/68#issuecomment-258383323

### CODE REVIEW

**Comment by jsuna** [comment]
Awesome! I see no issues.. @jcasner should probably also have a look!

**Comment by jsuna** [comment]
oh, are we wanting this to go into `integration` rather than `master`?

**Comment by Protosac** [comment]
Nope, just need to merge it here. The requirements file will take care of the rest.

**Comment by jcasner** [comment]
`master` is effectively deprecated from our use. I think this does need to go into `integration` so that it makes its way out to `qa` and `production` eventually. Or maybe I misunderstood the comment?

**Comment by jcasner** [comment]
Shit, ok, nm. I was thinking this was in `sindeo/sindeo`. Yes, this can go to `master`. I lied. Sorry about that!

**Comment by jsuna** [comment]
ha, same here..

**Pull request merged**
